name: build_image

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

env:
  REGISTRY: ghcr.io
  REPOSITORY_URI_WEB: iotexproject/safe-transaction-web
  REPOSITORY_URI_NGINX: iotexproject/safe-transaction-nginx

jobs:
  build_docker_image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
        
      - name: Setup Docker and Colima
        if: startsWith(matrix.os, 'macos-latest') == true
        run: |
          brew install docker colima
          colima start
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta-web
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_URI_WEB }}


      - name: Build and push Docker image web
        id: build-and-push-web
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          file: ./docker/web/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          

      - name: Extract Docker metadata
        id: meta-nginx
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_URI_NGINX }}
      - name: Build and push Docker image nginx
        id: build-and-push-nginx
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: ./docker/nginx/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}
